### ISSUE TITLE
Anyone can successfully submit the results? 

### ISSUE THREAD

**Issue by ToddBear** [lynetcha/completion3d#27]
The page remains in 'Please be patient while we verify that the file contents match the expected format.' for quite a long time. I wonder whether the server is broken.

**Comment by junshutang** [comment]
I agree with you.

**Comment by prajwalsingh** [comment]
Any updates regarding this issue?

**Comment by ark1234** [comment]
Please have a look on it

**Comment by ToddBear** [comment]
The website is broken. I can not access it.

**Comment by ninasinger** [comment]
Have any of you been successful in submitting? Are there any other completion datasets that are accepting submissions?

Edit: FYI for anyone still interested, I was just informed by the authors that this benchmark is no longer maintained.

**Comment by beibeirory** [comment]
> The website is broken. I can not access it.

Have you successfully got the validation results? @ToddBear

**Comment by KushanRaj** [comment]
Was there any conclusion to this?

**Comment by ToddBear** [comment]
> Was there any conclusion to this?

The website won't be accessible anymore.

**Comment by KushanRaj** [comment]
> > Was there any conclusion to this?
> 
> The website won't be accessible anymore.

Is there any other portal for submission, or anywhere we can get access to the test gt for this dataset?

**Comment by ToddBear** [comment]
> > > Was there any conclusion to this?
> > 
> > 
> > The website won't be accessible anymore.
> 
> Is there any other portal for submission, or anywhere we can get access to the test gt for this dataset?

Probably no, as far as i know. I suggest that you should try other datasets.
