### ISSUE TITLE
Unable to download the dataset

### ISSUE THREAD

**Issue by symphonylyh** [lynetcha/completion3d#28]
Is this dataset still available for downloading? The link in the [project webpage](https://completion3d.stanford.edu/) has no response...

**Comment by jamesbraza** [comment]
Scrolling down in the page linked above, there are two datasets linked:
- 2048K: http://download.cs.stanford.edu/downloads/completion3d/dataset2019.zip
- 16384K: http://download.cs.stanford.edu/downloads/completion3d/shapenet16K2019.zip

Pasting those into a new tab downloaded the datasets as `.zip` files.  Note that they're both large files (1.59 GB and 5.82 GB), so the download 10+ minutes.

Disclaimer: I am not associated with Completion 3D, I am just looking at the datasets.

**Comment by aditya-jha13** [comment]
I am unable to download the dataset. Kindly look into this issue!

**Comment by jaswanthbjk** [comment]
The website says 503 Unavailable. Is there any alternative link to download the dataset ??

**Comment by arxidinakbar** [comment]
> The website says 503 Unavailable. Is there any alternative link to download the dataset ??

Hi, did you find any solution for this？

**Comment by arxidinakbar** [comment]
> Scrolling down in the page linked above, there are two datasets linked:
> 
> * 2048K: http://download.cs.stanford.edu/downloads/completion3d/dataset2019.zip
> * 16384K: http://download.cs.stanford.edu/downloads/completion3d/shapenet16K2019.zip
> 
> Pasting those into a new tab downloaded the datasets as `.zip` files. Note that they're both large files (1.59 GB and 5.82 GB), so the download 10+ minutes.
> 
> Disclaimer: I am not associated with Completion 3D, I am just looking at the datasets.

Thank you for helping ：)

**Comment by Halo2Tang** [comment]
@jamesbraza Sir,do you know how to download this dataset now? The link you provided seems to be invalid.

**Comment by jamesbraza** [comment]
The link from above are all no longer working for me either (June 27 2023) 😢 sorry @THTHK354

**Comment by lynetcha** [comment]
The links should be working
