### ISSUE TITLE
Unable to download the dataset

### ISSUE THREAD

**Issue by harishkool** [lynetcha/completion3d#4]
Hi,

I am unable to download the dataset. I am getting the '**Not Found**' webpage error. Kindly help.

**Comment by XLechter** [comment]
meet the same problem and can not open the project page sometimes.

**Comment by lynetcha** [comment]
The dataset link has been updated and should be working now. Let us know if you are still encountering issues. We also updated the code base with instructions on how to create a submission file.

**Comment by harishkool** [comment]
I am able to download the dataset now. Thank you.

**Comment by HoweHuang** [comment]
same problem and can not download the dataset now
