### ISSUE TITLE
question about pytorch setup

### ISSUE THREAD

**Issue by amiltonwong** [lynetcha/completion3d#7]
Hi, all,

I followed the pytorch-setup.md. However, when I build the EMD module, I got this building [error](https://gist.githubusercontent.com/amiltonwong/11ac8a9483b66c0c563865f173edc69f/raw/6753a69c3aeded376ca5264128e2a87a54936e00/EMD_error). My version of pytorch is python3-pytorch-0.4.1.

According to the building [step](https://github.com/lynetcha/completion3d/blob/master/pytorch-setup.md#build-emd-module-xia-et-al---known-issues-for-setups-other-than-python-27--pytorch-0111---feel-free-to-submit-a-pull-request-with-fixes-for-other-setups) on EMD module,  only python-27-pytorch-0.11.1 is suggested. But pytorch-0.11.1 seems quite old. 

Any suggestion to fix this issue?

THX!

**Comment by lynetcha** [comment]
I just pushed a fix to the compilation issue. Let me know if it works for you.
But note that EMD in pytorch is currently disabled due to known issues (see [this ](https://github.com/meder411/PyTorch-EMDLoss)for instance)

**Comment by amiltonwong** [comment]
@lynetcha,
Thanks for your reply. The building for EMD module succeeds.
